# 정상 데이터 csv 파일 모두 불러오기

In [ ]:
# Data0_SVM.ipynp 파일 보기

import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import random
%matplotlib inline

In [ ]:
# 정상 데이터 csv 파일들

linklist = ['WELL-00001_20170201020207.csv',
'WELL-00001_20170201070114.csv',
'WELL-00001_20170201120124.csv',
'WELL-00001_20170201170311.csv',
'WELL-00001_20170201220228.csv',
'WELL-00001_20170202030343.csv',
'WELL-00001_20170202080239.csv',
'WELL-00001_20170218010146.csv',
'WELL-00001_20170218060218.csv',
'WELL-00001_20170218110218.csv',
'WELL-00001_20170218160135.csv',
'WELL-00001_20170219020042.csv',
'WELL-00001_20170219070031.csv',
'WELL-00001_20170219120021.csv',
'WELL-00001_20170219170053.csv',
'WELL-00001_20170219220332.csv',
'WELL-00001_20170421100251.csv',
'WELL-00001_20170422040000.csv',
'WELL-00001_20170424180042.csv',
'WELL-00001_20170424230156.csv',
'WELL-00001_20170425040207.csv',
'WELL-00001_20170425090343.csv',
'WELL-00001_20170425140042.csv',
'WELL-00001_20170520190000.csv',
'WELL-00001_20170521000000.csv',
'WELL-00001_20170521050000.csv',
'WELL-00001_20170521100000.csv',
'WELL-00001_20170521150000.csv',
'WELL-00001_20170521200000.csv',
'WELL-00001_20170522010000.csv',
'WELL-00001_20170522060000.csv',
'WELL-00001_20170522110000.csv',
'WELL-00001_20170522160000.csv',
'WELL-00001_20170522210000.csv',
'WELL-00001_20170523020012.csv',
'WELL-00001_20170523070000.csv',
'WELL-00001_20170523120000.csv',
'WELL-00001_20170523170000.csv',
'WELL-00001_20170523220000.csv',
'WELL-00001_20170524030000.csv',
'WELL-00001_20170524080000.csv',
'WELL-00001_20170524130000.csv',
'WELL-00001_20170524180000.csv',
'WELL-00001_20170524230000.csv',
'WELL-00001_20170525040000.csv',
'WELL-00001_20170525090000.csv',
'WELL-00001_20170525140000.csv',
'WELL-00001_20170525190000.csv',
'WELL-00001_20170526000000.csv',
'WELL-00001_20170526050000.csv',
'WELL-00001_20170526100000.csv',
'WELL-00001_20170526150000.csv',
'WELL-00001_20170526200000.csv',
'WELL-00001_20170527010000.csv',
'WELL-00001_20170527060000.csv',
'WELL-00001_20170527110000.csv',
'WELL-00001_20170527160000.csv',
'WELL-00001_20170527210000.csv',
'WELL-00001_20170528020000.csv',
'WELL-00001_20170528070000.csv',
'WELL-00001_20170528120000.csv',
'WELL-00001_20170528170000.csv',
'WELL-00001_20170528220000.csv',
'WELL-00001_20170626100246.csv',
'WELL-00001_20170626150123.csv',
'WELL-00001_20170626200135.csv',
'WELL-00001_20170627010333.csv',
'WELL-00001_20170823050000.csv',
'WELL-00001_20170823150000.csv',
'WELL-00001_20170823200000.csv',
'WELL-00001_20170824010000.csv',
'WELL-00001_20170824060000.csv',
'WELL-00001_20170824110000.csv',
'WELL-00001_20170824160000.csv',
'WELL-00001_20170824210000.csv',
'WELL-00001_20170825020000.csv',
'WELL-00001_20170825070000.csv',
'WELL-00001_20170825120000.csv',
'WELL-00001_20170825170000.csv',
'WELL-00001_20170825220000.csv',
'WELL-00001_20170826030000.csv',
'WELL-00001_20170826080000.csv',
'WELL-00001_20170826130000.csv',
'WELL-00001_20170826180000.csv',
'WELL-00001_20170826230000.csv',
'WELL-00001_20170827040000.csv',
'WELL-00001_20170827090000.csv',
'WELL-00001_20170827140000.csv',
'WELL-00001_20170827190000.csv',
'WELL-00001_20170828000000.csv',
'WELL-00001_20170828050000.csv',
'WELL-00001_20170828100000.csv',
'WELL-00002_20131211230015.csv',
'WELL-00002_20131212010148.csv',
'WELL-00002_20131212030000.csv',
'WELL-00002_20131212050000.csv',
'WELL-00002_20131212070005.csv',
'WELL-00002_20131214160127.csv',
'WELL-00002_20131214180036.csv',
'WELL-00002_20131214200030.csv',
'WELL-00002_20170209120022.csv',
'WELL-00002_20170209170152.csv',
'WELL-00002_20170209220033.csv',
'WELL-00002_20170210030033.csv',
'WELL-00002_20170210080407.csv',
'WELL-00002_20170210130152.csv',
'WELL-00002_20170210180033.csv',
'WELL-00002_20170210230203.csv',
'WELL-00002_20170211040225.csv',
'WELL-00002_20170211090129.csv',
'WELL-00002_20170211140152.csv',
'WELL-00002_20170211190129.csv',
'WELL-00002_20170212000141.csv',
'WELL-00002_20170212050225.csv',
'WELL-00002_20170212100203.csv',
'WELL-00002_20170212150407.csv',
'WELL-00002_20170212200429.csv',
'WELL-00002_20170213010322.csv',
'WELL-00002_20170213060225.csv',
'WELL-00002_20170213110344.csv',
'WELL-00002_20170213160107.csv',
'WELL-00002_20170213210214.csv',
'WELL-00002_20170214020118.csv',
'WELL-00002_20170214070141.csv',
'WELL-00002_20170214120056.csv',
'WELL-00002_20170214170044.csv',
'WELL-00002_20170214220322.csv',
'WELL-00002_20170215030259.csv',
'WELL-00002_20170215080056.csv',
'WELL-00002_20170215130214.csv',
'WELL-00002_20170215180118.csv',
'WELL-00002_20170215230129.csv',
'WELL-00002_20170216040141.csv',
'WELL-00002_20170216090118.csv',
'WELL-00002_20170216140152.csv',
'WELL-00002_20170216190214.csv',
'WELL-00002_20170217000107.csv',
'WELL-00002_20170217050451.csv',
'WELL-00002_20170217100355.csv',
'WELL-00002_20170217150248.csv',
'WELL-00002_20170217200225.csv',
'WELL-00002_20170218010237.csv',
'WELL-00002_20170218060225.csv',
'WELL-00002_20170218110022.csv',
'WELL-00002_20170218160214.csv',
'WELL-00002_20170219020033.csv',
'WELL-00002_20170219070129.csv',
'WELL-00002_20170219120152.csv',
'WELL-00002_20170219170203.csv',
'WELL-00002_20170219220214.csv',
'WELL-00002_20170307200031.csv',
'WELL-00002_20170308010103.csv',
'WELL-00002_20170308060042.csv',
'WELL-00002_20170308110124.csv',
'WELL-00002_20170308160353.csv',
'WELL-00002_20170308210218.csv',
'WELL-00002_20170309020218.csv',
'WELL-00002_20170309070218.csv',
'WELL-00002_20170309120156.csv',
'WELL-00002_20170309170218.csv',
'WELL-00002_20170309220207.csv',
'WELL-00002_20170310030146.csv',
'WELL-00002_20170310080518.csv',
'WELL-00002_20170310130321.csv',
'WELL-00002_20170310180103.csv',
'WELL-00002_20170310230042.csv',
'WELL-00002_20170404030000.csv',
'WELL-00002_20170404080045.csv',
'WELL-00002_20170404130000.csv',
'WELL-00002_20170404180000.csv',
'WELL-00002_20170404230000.csv',
'WELL-00002_20170405040000.csv',
'WELL-00002_20170405090000.csv',
'WELL-00002_20170405140000.csv',
'WELL-00002_20170405190000.csv',
'WELL-00002_20170406000000.csv',
'WELL-00002_20170406050000.csv',
'WELL-00002_20170406100000.csv',
'WELL-00002_20170406150000.csv',
'WELL-00002_20170406200000.csv',
'WELL-00002_20170611000108.csv',
'WELL-00002_20170611050011.csv',
'WELL-00002_20170611100000.csv',
'WELL-00002_20170611150000.csv',
'WELL-00002_20170611200000.csv',
'WELL-00002_20170612010000.csv',
'WELL-00002_20170612060057.csv',
'WELL-00002_20170612110022.csv',
'WELL-00002_20170612160022.csv',
'WELL-00002_20170612210000.csv',
'WELL-00002_20170613020022.csv',
'WELL-00002_20170613070011.csv',
'WELL-00002_20170613120000.csv',
'WELL-00002_20170613170000.csv',
'WELL-00002_20170613220000.csv',
'WELL-00002_20170614030000.csv',
'WELL-00002_20170614080057.csv',
'WELL-00002_20170614130000.csv',
'WELL-00002_20170614180000.csv',
'WELL-00002_20170614230200.csv',
'WELL-00002_20170615040032.csv',
'WELL-00002_20170615090400.csv',
'WELL-00002_20170615140021.csv',
'WELL-00002_20170615190127.csv',
'WELL-00002_20170616000149.csv',
'WELL-00002_20170616050043.csv',
'WELL-00002_20170616100516.csv',
'WELL-00002_20170616150211.csv',
'WELL-00002_20170616200349.csv',
'WELL-00002_20170617010127.csv',
'WELL-00002_20170617060043.csv',
'WELL-00002_20170617110221.csv',
'WELL-00002_20170617160149.csv',
'WELL-00002_20170617220127.csv',
'WELL-00002_20170618020105.csv',
'WELL-00002_20170618070105.csv',
'WELL-00002_20170618120600.csv',
'WELL-00002_20170618170211.csv',
'WELL-00002_20170618220043.csv',
'WELL-00002_20170619030032.csv',
'WELL-00002_20170619080054.csv',
'WELL-00002_20170619130021.csv',
'WELL-00002_20170619180149.csv',
'WELL-00002_20170619230043.csv',
'WELL-00002_20170620040505.csv',
'WELL-00002_20170620090254.csv',
'WELL-00002_20170620140116.csv',
'WELL-00002_20170620190211.csv',
'WELL-00002_20170620230109.csv',
'WELL-00002_20170621030054.csv',
'WELL-00002_20170621080422.csv',
'WELL-00002_20170621130116.csv',
'WELL-00002_20170621180032.csv',
'WELL-00002_20170621230054.csv',
'WELL-00002_20170622040105.csv',
'WELL-00002_20170622090043.csv',
'WELL-00002_20170622140127.csv',
'WELL-00002_20170622190316.csv',
'WELL-00002_20170623000305.csv',
'WELL-00002_20170623050021.csv',
'WELL-00002_20170623100032.csv',
'WELL-00002_20170623150127.csv',
'WELL-00002_20170623200211.csv',
'WELL-00002_20170624010032.csv',
'WELL-00002_20170624060127.csv',
'WELL-00002_20170624110021.csv',
'WELL-00002_20170624160054.csv',
'WELL-00002_20170624210211.csv',
'WELL-00002_20170625020200.csv',
'WELL-00002_20170625070243.csv',
'WELL-00002_20170625120032.csv',
'WELL-00002_20170625170232.csv',
'WELL-00002_20170625220127.csv',
'WELL-00002_20170626030043.csv',
'WELL-00002_20170626080149.csv',
'WELL-00002_20170626130032.csv',
'WELL-00002_20170626180138.csv',
'WELL-00002_20170626230316.csv',
'WELL-00002_20170804210000.csv',
'WELL-00002_20170805020000.csv',
'WELL-00002_20170805070000.csv',
'WELL-00002_20170805120000.csv',
'WELL-00002_20170805170000.csv',
'WELL-00002_20170805220000.csv',
'WELL-00002_20170806030000.csv',
'WELL-00002_20170806080000.csv',
'WELL-00002_20170806130000.csv',
'WELL-00002_20170806180000.csv',
'WELL-00002_20170806230000.csv',
'WELL-00002_20170807040000.csv',
'WELL-00002_20170807090000.csv',
'WELL-00002_20170807140000.csv',
'WELL-00002_20170807190000.csv',
'WELL-00002_20170808000000.csv',
'WELL-00002_20170808050000.csv',
'WELL-00002_20170808100000.csv',
'WELL-00002_20170808150000.csv',
'WELL-00002_20170808200026.csv',
'WELL-00002_20170809010000.csv',
'WELL-00002_20170809060000.csv',
'WELL-00002_20170809110000.csv',
'WELL-00002_20170809160026.csv',
'WELL-00002_20170809210000.csv',
'WELL-00002_20170810020026.csv',
'WELL-00002_20170810070000.csv',
'WELL-00002_20170810120000.csv',
'WELL-00002_20170810170000.csv',
'WELL-00002_20170810220000.csv',
'WELL-00002_20170811030000.csv',
'WELL-00002_20170811080000.csv',
'WELL-00002_20170811130000.csv',
'WELL-00002_20170811180000.csv',
'WELL-00002_20170811230000.csv',
'WELL-00002_20170812040000.csv',
'WELL-00002_20170812090000.csv',
'WELL-00002_20170812140000.csv',
'WELL-00002_20170812190000.csv',
'WELL-00002_20170813000000.csv',
'WELL-00002_20170813050000.csv',
'WELL-00002_20170813100000.csv',
'WELL-00002_20170813150000.csv',
'WELL-00003_20170514010000.csv',
'WELL-00003_20170514060000.csv',
'WELL-00003_20170514110000.csv',
'WELL-00003_20170514160000.csv',
'WELL-00003_20170807100000.csv',
'WELL-00003_20170812020116.csv',
'WELL-00003_20170812070038.csv',
'WELL-00003_20170812120000.csv',
'WELL-00003_20170812170025.csv',
'WELL-00003_20170812220116.csv',
'WELL-00003_20170813030000.csv',
'WELL-00003_20170813080105.csv',
'WELL-00003_20170813130131.csv',
'WELL-00003_20170813180118.csv',
'WELL-00003_20170820230053.csv',
'WELL-00003_20170821040114.csv',
'WELL-00003_20170821090300.csv',
'WELL-00003_20170821140207.csv',
'WELL-00003_20170914110000.csv',
'WELL-00003_20170914160000.csv',
'WELL-00003_20170914210000.csv',
'WELL-00003_20170915020000.csv',
'WELL-00003_20170915070000.csv',
'WELL-00003_20170915120000.csv',
'WELL-00003_20170915170000.csv',
'WELL-00003_20170915220000.csv',
'WELL-00004_20140806220033.csv',
'WELL-00004_20140807000129.csv',
'WELL-00004_20140807020107.csv',
'WELL-00004_20140807040137.csv',
'WELL-00004_20140807060141.csv',
'WELL-00004_20140807080055.csv',
'WELL-00004_20140807100112.csv',
'WELL-00004_20140807120112.csv',
'WELL-00004_20140807140038.csv',
'WELL-00004_20140807160311.csv',
'WELL-00004_20140807180050.csv',
'WELL-00004_20140807200042.csv',
'WELL-00005_20170331060014.csv',
'WELL-00005_20170331110000.csv',
'WELL-00005_20170331160000.csv',
'WELL-00005_20170331210112.csv',
'WELL-00005_20170401020000.csv',
'WELL-00005_20170401070000.csv',
'WELL-00005_20170401120141.csv',
'WELL-00005_20170401170000.csv',
'WELL-00005_20170401220156.csv',
'WELL-00005_20170402030029.csv',
'WELL-00005_20170402080043.csv',
'WELL-00005_20170402130029.csv',
'WELL-00005_20170402180043.csv',
'WELL-00005_20170402230127.csv',
'WELL-00005_20170403040000.csv',
'WELL-00005_20170403090000.csv',
'WELL-00005_20170403140000.csv',
'WELL-00005_20170403190000.csv',
'WELL-00005_20170404000043.csv',
'WELL-00005_20170516050046.csv',
'WELL-00005_20170516080038.csv',
'WELL-00005_20170516110000.csv',
'WELL-00005_20170516140007.csv',
'WELL-00005_20170516170000.csv',
'WELL-00005_20170516200038.csv',
'WELL-00005_20170516230000.csv',
'WELL-00005_20170812110000.csv',
'WELL-00005_20170812140000.csv',
'WELL-00005_20170812170000.csv',
'WELL-00005_20170812200000.csv',
'WELL-00005_20170812230000.csv',
'WELL-00005_20170813020000.csv',
'WELL-00005_20170813050000.csv',
'WELL-00005_20170813080000.csv',
'WELL-00005_20170813110000.csv',
'WELL-00005_20170813140000.csv',
'WELL-00005_20170813170000.csv',
'WELL-00005_20170813200000.csv',
'WELL-00005_20170813230000.csv',
'WELL-00005_20170814020000.csv',
'WELL-00005_20170814050000.csv',
'WELL-00005_20170814080000.csv',
'WELL-00005_20170814110000.csv',
'WELL-00005_20170814140000.csv',
'WELL-00005_20170814170000.csv',
'WELL-00005_20170814200000.csv',
'WELL-00005_20170814230000.csv',
'WELL-00005_20170815050000.csv',
'WELL-00005_20170815080000.csv',
'WELL-00005_20170815110000.csv',
'WELL-00005_20170815140000.csv',
'WELL-00005_20170815170000.csv',
'WELL-00005_20170815200000.csv',
'WELL-00005_20170815230000.csv',
'WELL-00005_20170816020000.csv',
'WELL-00005_20170816050000.csv',
'WELL-00005_20170816080000.csv',
'WELL-00005_20170816110000.csv',
'WELL-00005_20170816140000.csv',
'WELL-00005_20170816170000.csv',
'WELL-00005_20170816200000.csv',
'WELL-00005_20170816230000.csv',
'WELL-00005_20170817020000.csv',
'WELL-00005_20170817050000.csv',
'WELL-00005_20170817080000.csv',
'WELL-00005_20170817110000.csv',
'WELL-00005_20170817140000.csv',
'WELL-00005_20170817170000.csv',
'WELL-00005_20170817200000.csv',
'WELL-00005_20170830060000.csv',
'WELL-00005_20170830090000.csv',
'WELL-00005_20170830120000.csv',
'WELL-00005_20170830150000.csv',
'WELL-00005_20170830180000.csv',
'WELL-00005_20170830210000.csv',
'WELL-00005_20170910030004.csv',
'WELL-00005_20170910050000.csv',
'WELL-00005_20170910070000.csv',
'WELL-00005_20170910090000.csv',
'WELL-00005_20170910110000.csv',
'WELL-00005_20170910130000.csv',
'WELL-00006_20170206220031.csv',
'WELL-00006_20170207030135.csv',
'WELL-00006_20170207080124.csv',
'WELL-00006_20170207130228.csv',
'WELL-00006_20170207180042.csv',
'WELL-00006_20170207230207.csv',
'WELL-00006_20170208040124.csv',
'WELL-00006_20170208090053.csv',
'WELL-00006_20170208140146.csv',
'WELL-00006_20170208190207.csv',
'WELL-00006_20170209000114.csv',
'WELL-00006_20170209050042.csv',
'WELL-00006_20170209100207.csv',
'WELL-00006_20170209150146.csv',
'WELL-00006_20170209200114.csv',
'WELL-00006_20170210010135.csv',
'WELL-00006_20170222000000.csv',
'WELL-00006_20170222050000.csv',
'WELL-00006_20170222100000.csv',
'WELL-00006_20170222150000.csv',
'WELL-00006_20170222200000.csv',
'WELL-00006_20170223010000.csv',
'WELL-00006_20170223060000.csv',
'WELL-00006_20170223110000.csv',
'WELL-00006_20170223160000.csv',
'WELL-00006_20170223210000.csv',
'WELL-00006_20170224020000.csv',
'WELL-00006_20170224070000.csv',
'WELL-00006_20170224120025.csv',
'WELL-00006_20170224170000.csv',
'WELL-00006_20170505210021.csv',
'WELL-00006_20170506020103.csv',
'WELL-00006_20170506070114.csv',
'WELL-00006_20170506120042.csv',
'WELL-00006_20170506170053.csv',
'WELL-00006_20170506220103.csv',
'WELL-00006_20170507030249.csv',
'WELL-00006_20170507080124.csv',
'WELL-00006_20170507130135.csv',
'WELL-00006_20170507180103.csv',
'WELL-00006_20170507230053.csv',
'WELL-00006_20170508040021.csv',
'WELL-00006_20170508090031.csv',
'WELL-00006_20170508140053.csv',
'WELL-00006_20170508190053.csv',
'WELL-00006_20170509000053.csv',
'WELL-00006_20170509050031.csv',
'WELL-00006_20170509100135.csv',
'WELL-00006_20170509150042.csv',
'WELL-00006_20170509200135.csv',
'WELL-00006_20170815060000.csv',
'WELL-00006_20170815110000.csv',
'WELL-00006_20170815160000.csv',
'WELL-00006_20170815210000.csv',
'WELL-00006_20170816020000.csv',
'WELL-00006_20170816070000.csv',
'WELL-00006_20170816120000.csv',
'WELL-00006_20170816170000.csv',
'WELL-00006_20170816220000.csv',
'WELL-00006_20170817030000.csv',
'WELL-00006_20170817080000.csv',
'WELL-00006_20170817130000.csv',
'WELL-00006_20170817180000.csv',
'WELL-00006_20170817230000.csv',
'WELL-00006_20170818040000.csv',
'WELL-00006_20170818090000.csv',
'WELL-00006_20170818140000.csv',
'WELL-00006_20170818190000.csv',
'WELL-00006_20170819000000.csv',
'WELL-00006_20170819050000.csv',
'WELL-00006_20170819100000.csv',
'WELL-00006_20170819150000.csv',
'WELL-00006_20170819200000.csv',
'WELL-00006_20170820010000.csv',
'WELL-00006_20170820060000.csv',
'WELL-00006_20170820110000.csv',
'WELL-00006_20170820160000.csv',
'WELL-00006_20170820210000.csv',
'WELL-00006_20170821020000.csv',
'WELL-00006_20170821070000.csv',
'WELL-00006_20170821120000.csv',
'WELL-00006_20170821170000.csv',
'WELL-00006_20170821220000.csv',
'WELL-00006_20170822030000.csv',
'WELL-00006_20170822080000.csv',
'WELL-00006_20170822130000.csv',
'WELL-00006_20170822180000.csv',
'WELL-00006_20170822230000.csv',
'WELL-00006_20170823040000.csv',
'WELL-00006_20170823090000.csv',
'WELL-00006_20170823140000.csv',
'WELL-00006_20170823190000.csv',
'WELL-00006_20170824000000.csv',
'WELL-00006_20170824050000.csv',
'WELL-00006_20170824100000.csv',
'WELL-00006_20170824150000.csv',
'WELL-00006_20170824200135.csv',
'WELL-00006_20170825010042.csv',
'WELL-00006_20170825060135.csv',
'WELL-00006_20170825110249.csv',
'WELL-00006_20170825160135.csv',
'WELL-00006_20170825210053.csv',
'WELL-00006_20170826020207.csv',
'WELL-00006_20170826070135.csv',
'WELL-00006_20170826120103.csv',
'WELL-00006_20170826170103.csv',
'WELL-00006_20170826220114.csv',
'WELL-00006_20170827030218.csv',
'WELL-00006_20170827080114.csv',
'WELL-00006_20170827130321.csv',
'WELL-00006_20170827180146.csv',
'WELL-00006_20170827230218.csv',
'WELL-00006_20170828040343.csv',
'WELL-00006_20170828090311.csv',
'WELL-00006_20170828140031.csv',
'WELL-00007_20170801180000.csv',
'WELL-00007_20170801200000.csv',
'WELL-00008_20170610220246.csv',
'WELL-00008_20170611030246.csv',
'WELL-00008_20170611080445.csv',
'WELL-00008_20170611130123.csv',
'WELL-00008_20170611180123.csv',
'WELL-00008_20170611230123.csv',
'WELL-00008_20170612040000.csv',
'WELL-00008_20170612090246.csv',
'WELL-00008_20170612140047.csv',
'WELL-00008_20170612190111.csv',
'WELL-00008_20170613000222.csv',
'WELL-00008_20170613220222.csv',
'WELL-00008_20170614030135.csv',
'WELL-00008_20170614080246.csv',
'WELL-00008_20170614130135.csv',
'WELL-00008_20170614180123.csv',
'WELL-00008_20170614230333.csv',
'WELL-00008_20170615040123.csv',
'WELL-00008_20170615090234.csv',
'WELL-00008_20170615140310.csv',
'WELL-00008_20170615190111.csv',
'WELL-00008_20170629170123.csv',
'WELL-00008_20170629220321.csv',
'WELL-00008_20170630030222.csv',
'WELL-00008_20170630080310.csv',
'WELL-00008_20170630130246.csv',
'WELL-00008_20170630180321.csv',
'WELL-00008_20170630230146.csv',
'WELL-00008_20170701040210.csv',
'WELL-00008_20170701090222.csv',
'WELL-00008_20170701140135.csv',
'WELL-00008_20170701190222.csv',
'WELL-00008_20170702000246.csv',
'WELL-00008_20170702050135.csv',
'WELL-00008_20170702100222.csv',
'WELL-00008_20170702150532.csv',
'WELL-00008_20170702200135.csv',
'WELL-00008_20170703010445.csv',
'WELL-00008_20170703060123.csv',
'WELL-00008_20170816140222.csv',
'WELL-00008_20170816190321.csv',
'WELL-00008_20170817000146.csv',
'WELL-00008_20170817050135.csv',
'WELL-00008_20170817100246.csv',
'WELL-00008_20170817150222.csv',
'WELL-00008_20170817200123.csv',
'WELL-00008_20170818010222.csv',
'WELL-00008_20170818060210.csv',
'WELL-00008_20170818110258.csv',
'WELL-00008_20170818160123.csv',
'WELL-00008_20170818210310.csv',
'WELL-00008_20170819020123.csv',
'WELL-00008_20170819070246.csv',
'WELL-00008_20170819120210.csv',
'WELL-00008_20170914020321.csv',
'WELL-00008_20170914070222.csv',
'WELL-00008_20170914120246.csv']

In [ ]:
len(linklist)

594

In [ ]:
#데이터셋 모두 데이터프레임으로 변환 후 리스트에 담기
#594개 -> CPU 환경에서 6분 15초 소요
dflist=[]
for i in linklist:
  d = pd.read_csv('https://raw.githubusercontent.com/petrobras/3W/main/dataset/0/'+i)
  dflist.append(d)

dflist

[                        timestamp  P-PDG       P-TPT     T-TPT  P-MON-CKP  \
 0      2017-02-01 02:02:07.000000    0.0  10092110.0  119.0944  1609800.0
 1      2017-02-01 02:02:08.000000    0.0  10092000.0  119.0944  1618206.0
 2      2017-02-01 02:02:09.000000    0.0  10091890.0  119.0944  1626612.0
 3      2017-02-01 02:02:10.000000    0.0  10091780.0  119.0944  1635018.0
 4      2017-02-01 02:02:11.000000    0.0  10091670.0  119.0944  1643424.0
 ...                           ...    ...         ...       ...        ...
 17869  2017-02-01 06:59:56.000000    0.0  10014690.0  119.0453  1504822.0
 17870  2017-02-01 06:59:57.000000    0.0  10014690.0  119.0452  1510422.0
 17871  2017-02-01 06:59:58.000000    0.0  10014690.0  119.0451  1516023.0
 17872  2017-02-01 06:59:59.000000    0.0  10014690.0  119.0450  1521623.0
 17873  2017-02-01 07:00:00.000000    0.0  10014690.0  119.0449  1527223.0

        T-JUS-CKP  P-JUS-CKGL  T-JUS-CKGL  QGL  class
 0       84.59782   1564147.0         NaN  0.0      0
 1       84.58997   1564148.0         NaN  0.0      0
 2       84.58213   1564148.0         NaN  0.0      0
 3       84.57429   1564148.0         NaN  0.0      0
 4       84.56644   1564148.0         NaN  0.0      0
 ...          ...         ...         ...  ...    ...
 17869   83.44021   1567749.0         NaN  0.0      0
 17870   83.45413   1567749.0         NaN  0.0      0
 17871   83.46806   1567750.0         NaN  0.0      0
 17872   83.48199   1567750.0         NaN  0.0      0
 17873   83.49591   1567750.0         NaN  0.0      0

 [17874 rows x 10 columns],
                         timestamp  P-PDG       P-TPT     T-TPT  P-MON-CKP  \
 0      2017-02-01 07:01:14.000000    0.0  10014690.0  119.0370  1792808.0
 1      2017-02-01 07:01:15.000000    0.0  10014690.0  119.0369  1799358.0
 2      2017-02-01 07:01:16.000000    0.0  10014690.0  119.0368  1805908.0
 3      2017-02-01 07:01:17.000000    0.0  10014690.0  119.0367  1812459.0
 4      2017-02-01 07:01:18.000000    0.0  10014690.0  119.0365  1819009.0
 ...                           ...    ...         ...       ...        ...
 17922  2017-02-01 11:59:56.000000    0.0   9995892.0  118.9539  1721275.0
 17923  2017-02-01 11:59:57.000000    0.0   9995997.0  118.9532  1706487.0
 17924  2017-02-01 11:59:58.000000    0.0   9996102.0  118.9526  1691698.0
 17925  2017-02-01 11:59:59.000000    0.0   9996207.0  118.9519  1676909.0
 17926  2017-02-01 12:00:00.000000    0.0   9996312.0  118.9513  1662120.0

        T-JUS-CKP  P-JUS-CKGL  T-JUS-CKGL  QGL  class
 0       84.38242   1567765.0         NaN  0.0      0
 1       84.38877   1567765.0         NaN  0.0      0
 2       84.39512   1567765.0         NaN  0.0      0
 3       84.40147   1567765.0         NaN  0.0      0
 4       84.40782   1567766.0         NaN  0.0      0
 ...          ...         ...         ...  ...    ...
 17922   84.13712   1571381.0         NaN  0.0      0
 17923   84.12492   1571381.0         NaN  0.0      0
 17924   84.11272   1571381.0         NaN  0.0      0
 17925   84.10052   1571381.0         NaN  0.0      0
 17926   84.08832   1571381.0         NaN  0.0      0

 [17927 rows x 10 columns],
                         timestamp  P-PDG       P-TPT     T-TPT  P-MON-CKP  \
 0      2017-02-01 12:01:24.000000    0.0  10005130.0  118.9649  1664520.0
 1      2017-02-01 12:01:25.000000    0.0  10005240.0  118.9652  1669515.0
 2      2017-02-01 12:01:26.000000    0.0  10005340.0  118.9655  1691216.0
 3      2017-02-01 12:01:27.000000    0.0  10005450.0  118.9658  1712916.0
 4      2017-02-01 12:01:28.000000    0.0  10005550.0  118.9662  1734617.0
 ...                           ...    ...         ...       ...        ...
 17912  2017-02-01 16:59:56.000000    0.0   9998633.0  118.9278  1674176.0
 17913  2017-02-01 16:59:57.000000    0.0   9998586.0  118.9265  1613736.0
 17914  2017-02-01 16:59:58.000000    0.0   9998539.0  118.9252  1553295.0
 17915  2017-02-01 16:59:59.000000    0.0   9998492.0  118.9239  1492854.0
 17916  2017-02-01 17:00:00.000000    0.0   9998445.0  118.9225  1432413.0

        T-JUS-CKP  P-JUS-CKGL  T-JUS-CKGL  QGL  class
 0       83.75337   1571398.0         NaN  0.0      0
 1       83.75287   1571398.0         NaN  0.0      0
 2       83.79058   1571399.0         NaN  0.0      0
 3       83.82830   1571399.0         NaN  0.0      0
 4       83.86601   1571399.0         NaN  0.0      0
 ...          ...         ...         ...  ...    ...
 17912   84.11642   1574278.0         NaN  0.0      0
 17913   84.11539   1574278.0         NaN  0.0      0
 17914   84.11436   1574278.0         NaN  0.0      0
 17915   84.11333   1574278.0         NaN  0.0      0
 17916   84.11230   1574278.0         NaN  0.0      0

 [17917 rows x 10 columns],
                         timestamp  P-PDG      P-TPT     T-TPT  P-MON-CKP  \
 0      2017-02-01 17:03:11.000000    0.0  9989480.0  118.8682  1178354.0
 1      2017-02-01 17:03:12.000000    0.0  9989433.0  118.8683  1154844.0
 2      2017-02-01 17:03:13.000000    0.0  9989386.0  118.8685  1131335.0
 3      2017-02-01 17:03:14.000000    0.0  9989339.0  118.8686  1107826.0
 4      2017-02-01 17:03:15.000000    0.0  9989291.0  118.8688  1084317.0
 ...                           ...    ...        ...       ...        ...
 17805  2017-02-01 21:59:56.000000    0.0  9914938.0  118.7858  1875015.0
 17806  2017-02-01 21:59:57.000000    0.0  9914938.0  118.7858  1876133.0
 17807  2017-02-01 21:59:58.000000    0.0  9914938.0  118.7858  1877251.0
 17808  2017-02-01 21:59:59.000000    0.0  9914938.0  118.7858  1878369.0
 17809  2017-02-01 22:00:00.000000    0.0  9914938.0  118.7858  1879487.0

        T-JUS-CKP  P-JUS-CKGL  T-JUS-CKGL  QGL  class
 0       83.51107   1574288.0         NaN  0.0      0
 1       83.49551   1574288.0         NaN  0.0      0
 2       83.47994   1574288.0         NaN  0.0      0
 3       83.46438   1574288.0         NaN  0.0      0
 4       83.44881   1574288.0         NaN  0.0      0
 ...          ...         ...         ...  ...    ...
 17805   84.26986   1575191.0         NaN  0.0      0
 17806   84.28330   1575191.0         NaN  0.0      0
 17807   84.29675   1575191.0         NaN  0.0      0
 17808   84.31020   1575191.0         NaN  0.0      0
 17809   84.32365   1575191.0         NaN  0.0      0

 [17810 rows x 10 columns],
                         timestamp  P-PDG      P-TPT     T-TPT  P-MON-CKP  \
 0      2017-02-01 22:02:28.000000    0.0  9914938.0  118.7858  1425611.0
 1      2017-02-01 22:02:29.000000    0.0  9914938.0  118.7858  1436790.0
 2      2017-02-01 22:02:30.000000    0.0  9914938.0  118.7858  1447969.0
 3      2017-02-01 22:02:31.000000    0.0  9914938.0  118.7858  1459149.0
 4      2017-02-01 22:02:32.000000    0.0  9914938.0  118.7858  1470328.0
 ...                           ...    ...        ...       ...        ...
 17848  2017-02-02 02:59:56.000000    0.0  9906240.0  118.7920  1546544.0
 17849  2017-02-02 02:59:57.000000    0.0  9906281.0  118.7920  1516886.0
 17850  2017-02-02 02:59:58.000000    0.0  9906320.0  118.7919  1487228.0
 17851  2017-02-02 02:59:59.000000    0.0  9906360.0  118.7919  1457570.0
 17852  2017-02-02 03:00:00.000000    0.0  9906400.0  118.7919  1427913.0

        T-JUS-CKP  P-JUS-CKGL  T-JUS-CKGL  QGL  class
 0       83.22643   1575198.0         NaN  0.0      0
 1       83.23154   1575198.0         NaN  0.0      0
 2       83.23664   1575199.0         NaN  0.0      0
 3       83.24174   1575199.0         NaN  0.0      0
 4       83.24685   1575199.0         NaN  0.0      0
 ...          ...         ...         ...  ...    ...
 17848   83.74183   1577993.0         NaN  0.0      0
 17849   83.74252   1577993.0         NaN  0.0      0
 17850   83.74321   1577993.0         NaN  0.0      0
 17851   83.74390   1577993.0         NaN  0.0      0
 17852   83.74459   1577994.0         NaN  0.0      0

 [17853 rows x 10 columns],
                         timestamp  P-PDG      P-TPT     T-TPT  P-MON-CKP  \
 0      2017-02-02 03:03:43.000000    0.0  9914938.0  118.7874  1432759.0
 1      2017-02-02 03:03:44.000000    0.0  9914938.0  118.7874  1421402.0
 2      2017-02-02 03:03:45.000000    0.0  9914938.0  118.7874  1427637.0
 3      2017-02-02 03:03:46.000000    0.0  9914938.0  118.7874  1433872.0
 4      2017-02-02 03:03:47.000000    0.0  9914938.0  118.7874  1440106.0
 ...                           ...    ...        ...       ...        ...
 17773  2017-02-02 07:59:56.000000    0.0  9879874.0  118.7858  1351994.0
 17774  2017-02-02 07:59:57.000000    0.0  9879950.0  118.7858  1356782.0
 17775  2017-02-02 07:59:58.000000    0.0  9880027.0  118.7858  1361570.0
 17776  2017-02-02 07:59:59.000000    0.0  9880104.0  118.7858  1366358.0
 17777  2017-02-02 08:00:00.000000    0.0  9880180.0  118.7858  1371146.0

        T-JUS-CKP  P-JUS-CKGL  T-JUS-CKGL  QGL  class
 0       83.17275   1578039.0         NaN  0.0      0
 1       83.17943   1578039.0         NaN  0.0      0
 2       83.18610   1578040.0         NaN  0.0      0
 3       83.19279   1578040.0         NaN  0.0      0
 4       83.19946   1578040.0         NaN  0.0      0
 ...          ...         ...         ...  ...    ...
 17773   83.06614   1579495.0         NaN  0.0      0
 17774   83.07816   1579494.0         NaN  0.0      0
 17775   83.09019   1579494.0         NaN  0.0      0
 17776   83.10222   1579493.0         NaN  0.0      0
 17777   83.11424   1579492.0         NaN  0.0      0

 [17778 rows x 10 columns],
                         timestamp  P-PDG      P-TPT     T-TPT  P-MON-CKP  \
 0      2017-02-02 08:02:39.000000    0.0  9892381.0  118.7858  1294453.0
 1      2017-02-02 08:02:40.000000    0.0  9892457.0  118.7858  1298431.0
 2      2017-02-02 08:02:41.000000    0.0  9892534.0  118.7858  1302410.0
 3      2017-02-02 08:02:42.000000    0.0  9892610.0  118.7858  1306388.0
 4      2017-02-02 08:02:43.000000    0.0  9892687.0  118.7858  1310367.0
 ...                           ...    ...        ...       ...        ...
 17837  2017-02-02 12:59:56.000000    0.0  9857101.0  118.7858  1561218.0
 17838  2017-02-02 12:59:57.000000    0.0  9857269.0  118.7858  1571172.0
 17839  2017-02-02 12:59:58.000000    0.0  9857436.0  118.7858  1581127.0
 17840  2017-02-02 12:59:59.000000    0.0  9857604.0  118.7858  1591082.0
 17841  2017-02-02 13:00:00.000000    0.0  9857772.0  118.7858  1601037.0

        T-JUS-CKP  P-JUS-CKGL  T-JUS-CKGL  QGL  class
 0       83.55160   1579348.0         NaN  0.0      0
 1       83.54932   1579347.0         NaN  0.0      0
 2       83.54704   1579346.0         NaN  0.0      0
 3       83.54476   1579345.0         NaN  0.0      0
 4       83.54248   1579344.0         NaN  0.0      0
 ...          ...         ...         ...  ...    ...
 17837   83.68375   1563186.0         NaN  0.0      0
 17838   83.68604   1563185.0         NaN  0.0      0
 17839   83.68832   1563184.0         NaN  0.0      0
 17840   83.69059   1563183.0         NaN  0.0      0
 17841   83.69287   1563182.0         NaN  0.0      0

 [17842 rows x 10 columns],
                         timestamp  P-PDG       P-TPT     T-TPT  P-MON-CKP  \
 0      2017-02-18 01:01:46.000000    0.0  13878580.0  117.5749  5774038.0
 1      2017-02-18 01:01:47.000000    0.0  13878500.0  117.5749  5774512.0
 2      2017-02-18 01:01:48.000000    0.0  13878420.0  117.5749  5774986.0
 3      2017-02-18 01:01:49.000000    0.0  13878340.0  117.5749  5775460.0
 4      2017-02-18 01:01:50.000000    0.0  13878250.0  117.5749  5775935.0
 ...                           ...    ...         ...       ...        ...
 17890  2017-02-18 05:59:56.000000    0.0  13916910.0  117.7593  5827135.0
 17891  2017-02-18 05:59:57.000000    0.0  13916980.0  117.7592  5827460.0
 17892  2017-02-18 05:59:58.000000    0.0  13917040.0  117.7592  5827786.0
 17893  2017-02-18 05:59:59.000000    0.0  13917110.0  117.7591  5828112.0
 17894  2017-02-18 06:00:00.000000    0.0  13917170.0  117.7591  5828437.0

        T-JUS-CKP  P-JUS-CKGL  T-JUS-CKGL  QGL  class
 0       70.34729   3364544.0         NaN  0.0      0
 1       70.34695   3364544.0         NaN  0.0      0
 2       70.34663   3364544.0         NaN  0.0      0
 3       70.34629   3364544.0         NaN  0.0      0
 4       70.34595   3364544.0         NaN  0.0      0
 ...          ...         ...         ...  ...    ...
 17890   70.37634   3366587.0         NaN  0.0      0
 17891   70.37833   3366587.0         NaN  0.0      0
 17892   70.38033   3366588.0         NaN  0.0      0
 17893   70.38232   3366588.0         NaN  0.0      0
 17894   70.38431   3366588.0         NaN  0.0      0

 [17895 rows x 10 columns],
                         timestamp  P-PDG       P-TPT     T-TPT  P-MON-CKP  \
 0      2017-02-18 06:02:18.000000    0.0  13923900.0  117.7510  5859311.0
 1      2017-02-18 06:02:19.000000    0.0  13923850.0  117.7510  5859494.0
 2      2017-02-18 06:02:20.000000    0.0  13923810.0  117.7509  5859678.0
 3      2017-02-18 06:02:21.000000    0.0  13923760.0  117.7509  5859861.0
 4      2017-02-18 06:02:22.000000    0.0  13923710.0  117.7508  5860045.0
 ...                           ...    ...         ...       ...        ...
 17858  2017-02-18 10:59:56.000000    0.0  13864960.0  117.7277  5809567.0
 17859  2017-02-18 10:59:57.000000    0.0  13864960.0  117.7276  5809633.0
 17860  2017-02-18 10:59:58.000000    0.0  13864960.0  117.7275  5809699.0
 17861  2017-02-18 10:59:59.000000    0.0  13864960.0  117.7273  5809764.0
 17862  2017-02-18 11:00:00.000000    0.0  13864960.0  117.7272  5809830.0

        T-JUS-CKP  P-JUS-CKGL  T-JUS-CKGL  QGL  class
 0       70.39278   3366616.0         NaN  0.0      0
 1       70.39278   3366616.0         NaN  0.0      0
 2       70.39278   3366617.0         NaN  0.0      0
 3       70.39278   3366617.0         NaN  0.0      0
 4       70.39278   3366617.0         NaN  0.0      0
 ...          ...         ...         ...  ...    ...
 17858   70.42582   3370273.0         NaN  0.0      0
 17859   70.42747   3370274.0         NaN  0.0      0
 17860   70.42911   3370274.0         NaN  0.0      0
 17861   70.43076   3370274.0         NaN  0.0      0
 17862   70.43240   3370274.0         NaN  0.0      0

 [17863 rows x 10 columns],
                         timestamp  P-PDG       P-TPT     T-TPT  P-MON-CKP  \
 0      2017-02-18 11:02:18.000000    0.0  13864960.0  117.7095  5799931.0
 1      2017-02-18 11:02:19.000000    0.0  13864960.0  117.7094  5799721.0
 2      2017-02-18 11:02:20.000000    0.0  13864960.0  117.7093  5799512.0
 3      2017-02-18 11:02:21.000000    0.0  13864960.0  117.7092  5799303.0
 4      2017-02-18 11:02:22.000000    0.0  13864960.0  117.7090  5799094.0
 ...                           ...    ...         ...       ...        ...
 17858  2017-02-18 15:59:56.000000    0.0  13884900.0  117.7534  5765599.0
 17859  2017-02-18 15:59:57.000000    0.0  13884900.0  117.7533  5766333.0
 17860  2017-02-18 15:59:58.000000    0.0  13884900.0  117.7533  5767068.0
 17861  2017-02-18 15:59:59.000000    0.0  13884900.0  117.7533  5767802.0
 17862  2017-02-18 16:00:00.000000    0.0  13884900.0  117.7533  5768536.0

        T-JUS-CKP  P-JUS-CKGL  T-JUS-CKGL  QGL  class
 0       70.34012   3370303.0         NaN  0.0      0
 1       70.34214   3370303.0         NaN  0.0      0
 2       70.34417   3370303.0         NaN  0.0      0
 3       70.34619   3370303.0         NaN  0.0      0
 4       70.34822   3370303.0         NaN  0.0      0
 ...          ...         ...         ...  ...    ...
 17858   70.31807   3378587.0         NaN  0.0      0
 17859   70.31757   3378588.0         NaN  0.0      0
 17860   70.31708   3378588.0         NaN  0.0      0
 17861   70.31657   3378589.0         NaN  0.0      0
 17862   70.31608   3378589.0         NaN  0.0      0

 [17863 rows x 10 columns],
                         timestamp  P-PDG       P-TPT     T-TPT  P-MON-CKP  \
 0      2017-02-18 16:01:35.000000    0.0  13884900.0  117.7504  5825074.0
 1      2017-02-18 16:01:36.000000    0.0  13884900.0  117.7503  5823603.0
 2      2017-02-18 16:01:37.000000    0.0  13884900.0  117.7503  5822132.0
 3      2017-02-18 16:01:38.000000    0.0  13884900.0  117.7503  5820661.0
 4      2017-02-18 16:01:39.000000    0.0  13884900.0  117.7503  5819190.0
 ...                           ...    ...         ...       ...        ...
 17901  2017-02-18 20:59:56.000000    0.0  13828530.0  117.7312  5820763.0
 17902  2017-02-18 20:59:57.000000    0.0  13828660.0  117.7312  5821085.0
 17903  2017-02-18 20:59:58.000000    0.0  13828790.0  117.7312  5821407.0
 17904  2017-02-18 20:59:59.000000    0.0  13828920.0  117.7312  5821729.0
 17905  2017-02-18 21:00:00.000000    0.0  13829050.0  117.7312  5822051.0

        T-JUS-CKP  P-JUS-CKGL  T-JUS-CKGL  QGL  class
 0       70.43456   3378638.0         NaN  0.0      0
 1       70.43139   3378638.0         NaN  0.0      0
 2       70.42822   3378639.0         NaN  0.0      0
 3       70.42506   3378639.0         NaN  0.0      0
 4       70.42190   3378640.0         NaN  0.0      0
 ...          ...         ...         ...  ...    ...
 17901   70.06786   3385079.0         NaN  0.0      0
 17902   70.06860   3385079.0         NaN  0.0      0
 17903   70.06933   3385079.0         NaN  0.0      0
 17904   70.07005   3385079.0         NaN  0.0      0
 17905   70.07079   3385079.0         NaN  0.0      0

 [17906 rows x 10 columns],
                         timestamp  P-PDG       P-TPT     T-TPT  P-MON-CKP  \
 0      2017-02-19 02:00:42.000000    0.0  13805110.0  117.7151  5776934.0
 1      2017-02-19 02:00:43.000000    0.0  13805110.0  117.7151  5777114.0
 2      2017-02-19 02:00:44.000000    0.0  13805110.0  117.7152  5777295.0
 3      2017-02-19 02:00:45.000000    0.0  13805110.0  117.7152  5777477.0
 4      2017-02-19 02:00:46.000000    0.0  13805110.0  117.7153  5777657.0
 ...                           ...    ...         ...       ...        ...
 17954  2017-02-19 06:59:56.000000    0.0  13864960.0  117.6281  5764110.0
 17955  2017-02-19 06:59:57.000000    0.0  13864960.0  117.6280  5764079.0
 17956  2017-02-19 06:59:58.000000    0.0  13864960.0  117.6279  5764047.0
 17957  2017-02-19 06:59:59.000000    0.0  13864960.0  117.6278  5764016.0
 17958  2017-02-19 07:00:00.000000    0.0  13864960.0  117.6277  5763984.0

        T-JUS-CKP  P-JUS-CKGL  T-JUS-CKGL  QGL  class
 0       70.31982   3383970.0         NaN  0.0      0
 1       70.31937   3383970.0         NaN  0.0      0
 2       70.31892   3383970.0         NaN  0.0      0
 3       70.31848   3383970.0         NaN  0.0      0
 4       70.31803   3383970.0         NaN  0.0      0
 ...          ...         ...         ...  ...    ...
 17954   70.17936   3392841.0         NaN  0.0      0
 17955   70.17563   3392842.0         NaN  0.0      0
 17956   70.17189   3392842.0         NaN  0.0      0
 17957   70.16815   3392843.0         NaN  0.0      0
 17958   70.16442   3392843.0         NaN  0.0      0

 [17959 rows x 10 columns],
                         timestamp  P-PDG       P-TPT     T-TPT  P-MON-CKP  \
 0      2017-02-19 07:00:31.000000    0.0  13864960.0  117.6242  5776488.0
 1      2017-02-19 07:00:32.000000    0.0  13864960.0  117.6241  5777042.0
 2      2017-02-19 07:00:33.000000    0.0  13864960.0  117.6239  5777597.0
 3      2017-02-19 07:00:34.000000    0.0  13864960.0  117.6238  5778151.0
 4      2017-02-19 07:00:35.000000    0.0  13864960.0  117.6237  5778706.0
 ...                           ...    ...         ...       ...        ...
 17965  2017-02-19 11:59:56.000000    0.0  13884900.0  117.7103  5794019.0
 17966  2017-02-19 11:59:57.000000    0.0  13884900.0  117.7101  5793107.0
 17967  2017-02-19 11:59:58.000000    0.0  13884900.0  117.7099  5792195.0
 17968  2017-02-19 11:59:59.000000    0.0  13884900.0  117.7097  5791283.0
 17969  2017-02-19 12:00:00.000000    0.0  13884900.0  117.7095  5790371.0

        T-JUS-CKP  P-JUS-CKGL  T-JUS-CKGL  QGL  class
 0       70.21606   3392860.0         NaN  0.0      0
 1       70.21960   3392861.0         NaN  0.0      0

In [ ]:
dflist_c = dflist.copy()

for i in range(len(dflist_c), 0, -1):
  if (dflist_c[i-1].count()['P-TPT']<100) or (dflist_c[i-1].count()['T-TPT']<100) or (dflist_c[i-1].count()['P-MON-CKP']<100) or (dflist_c[i-1].count()['T-JUS-CKP']<100):
    del dflist_c[i-1]

len(dflist_c)

In [ ]:
for i in dflist_c:
  if len(i)<10000:
    print(len(i))